title: Portraits and Politics: The Romanov Winter Ball of 1903 # You will insert your title here.
email: your-email@example.com
description: Angel Ba√±uelos, Selina Cochran, Amanda Whitely. # Author names go here.

baseurl: "/romanovball" # the subpath of your site. Change it if the name of your repository is other than "mindoc"

twitter_username: jekyllrb
github_username:  jekyll

# Build settings

plugins:
  - jekyll-feed

collections:
  mindoc_media:
    output: true
    layout: 'image_description'
